# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 04:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('injection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagclaim',
            name='team_submit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='session',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='injection.Session'),
            preserve_default=False,
        ),
    ]
