# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0002_auto_20170621_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='team_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
