# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0003_auto_20170629_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagclaim',
            name='comment',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='flagclaim',
            name='current_team',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='flagclaim',
            name='previous_team',
            field=models.CharField(max_length=1024),
        ),
    ]
