# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0003_auto_20170621_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='IsSolved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='session',
            name='number_of_resets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='number_of_submission_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
